# Generated by Django 4.1 on 2022-08-28 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='person_id',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000000000000), django.core.validators.MaxValueValidator(99999999999999)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
